name: test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
        submodules: recursive

    - uses: buckaroobanzay/mtt@main
      with:
        test_mode: modrepo
        mapgen: "v7"
        mtt_filter: pandorabox_test
        git_game_repo: "https://github.com/luanti-org/minetest_game"
        additional_config: |
          areas.self_protection = true
          mesecon.luacontroller_lightweight_interrupts = true
          moreblocks.stairsplus_in_creative_inventory = false
          bridger_enable_trusses = true
          telemosaic_right_click_teleport = true
          secure.http_mods = monitoring,digistuff,blockexchange

    - name: 📧 Discord success notification
      continue-on-error: true
      env:
        DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
      uses: Ilshidur/action-discord@master
      with:
        args: '☑️ Integration test passed for branch `${{ github.ref }}` and commit `${{ github.sha }}`'

    - name: 📧 Discord failure notification
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
      uses: Ilshidur/action-discord@master
      with:
        args: '🚫 Integration test failed for branch `${{ github.ref }}` and commit `${{ github.sha }}`'
